$background = rgb(101418)
$foreground = rgb(e0e2e8)

$primary = rgb(99ccfa)
$on_primary = rgb(003351)

$secondary = rgb(b8c8da)
$on_secondary = rgb(23323f)

$tertiary = rgb(d1bfe7)
$on_tertiary = rgb(372a4a)

$surface = rgb(101418)
$surface_variant = rgb(42474e)
$on_surface = rgb(e0e2e8)

$error = rgb(ffb4ab)
$outline = rgb(8c9198)

$accent = rgb(d1bfe7)
