wallpaper {
monitor = DP-1
path = /home/daniel/Pictures/aafcf6cf516a7ed7d12265dabd58bfb1.jpg
fit_mode = cover
}
wallpaper {
monitor = HDMI-A-1
path = /home/daniel/Pictures/aafcf6cf516a7ed7d12265dabd58bfb1.jpg
fit_mode = cover
}


