$background = rgb({{colors.background.default.hex | replace: "#", ""}})
$foreground = rgb({{colors.on_background.default.hex | replace: "#", ""}})

$primary = rgb({{colors.primary.default.hex | replace: "#", ""}})
$on_primary = rgb({{colors.on_primary.default.hex | replace: "#", ""}})

$secondary = rgb({{colors.secondary.default.hex | replace: "#", ""}})
$on_secondary = rgb({{colors.on_secondary.default.hex | replace: "#", ""}})

$tertiary = rgb({{colors.tertiary.default.hex | replace: "#", ""}})
$on_tertiary = rgb({{colors.on_tertiary.default.hex | replace: "#", ""}})

$surface = rgb({{colors.surface.default.hex | replace: "#", ""}})
$surface_variant = rgb({{colors.surface_variant.default.hex | replace: "#", ""}})
$on_surface = rgb({{colors.on_surface.default.hex | replace: "#", ""}})

$error = rgb({{colors.error.default.hex | replace: "#", ""}})
$outline = rgb({{colors.outline.default.hex | replace: "#", ""}})

$accent = rgb({{colors.tertiary.default.hex | replace: "#", ""}})
